name: Merge main to dev

on:
  release:
    types: [created]

jobs:
  merge:
    runs-on: ubuntu-latest
    environment: commit-signing
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure SSH commit signing
        uses: shriyanss/verified-commit-action@v1
        with:
          ssh-private-key: ${{ secrets.JS_RECON_SIGNING_KEY }}
          commit-name: "js-recon-bot"
          commit-email: ${{ secrets.JS_RECON_SIGNING_EMAIL }}

      - name: Merge main into dev
        run: |
          git fetch origin main:main
          git fetch origin dev:dev
          git checkout dev
          git merge --no-ff -m "chore: merge changes after release $VERSION" main -X theirs || (git status && git diff && exit 0)
          git push origin dev
        env:
          VERSION: ${{ github.event.release.tag_name }}
